
x-mongo-env: &mongo-env
  environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=password

services:
  mongo_manager:
    image: mongo:6.0
    command: "--replSet rs0" # --keyFile /keys/mongodb/mongo-keyfile"
    networks:
      - mongo-network
    volumes:
      - mongo_manager:/data/db
      - ./keys/mongodb:/keys/mongodb
    # <<: *mongo-env
    deploy:
      replicas: 1
      # placement:
      #   constraints:
      #     - node.role == manager
    ports:
      - "27017:27017"

  mongo_worker:
    image: mongo:6.0
    command: "--replSet rs0" # --keyFile /keys/mongodb/mongo-keyfile"
    networks:
      - mongo-network
    volumes:
      - mongo_worker-data:/data/db
      - ./keys/mongodb:/keys/mongodb
    # <<: *mongo-env
    deploy:
      replicas: 1
      # placement:
      #   constraints:
      #     - node.role == worker

networks:
  mongo-network:
    driver: overlay
    attachable: true

volumes:
  mongo_manager:
  mongo_worker-data: