apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-mongos2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-mongos  # Change this to match the service selector
  template:
    metadata:
      labels:
        app: mongo-mongos  # Change this to match the service selector
    spec:
      nodeName: worker2
      containers:
        - name: mongos
          image: mongo:6.0
          command: ["mongos", "--configdb", "cfgReplSet/mongo-cfg:27017", "--port", "27017", "--bind_ip_all"]
