apiVersion: v1
kind: Service
metadata:
  name: mongo-cfg
  labels:
    app: mongo-cfg
spec:
  selector:
    app: mongo-cfg
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard1
spec:
  selector:
    app: mongo-shard1
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard2
spec:
  selector:
    app: mongo-shard2
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-shard3
spec:
  selector:
    app: mongo-shard3
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-mongos
spec:
  selector:
    app: mongo-mongos
  ports:
    - port: 27017
      targetPort: 27017
