apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-shard1
spec:
  serviceName: "mongo-shard1"
  replicas: 1
  selector:
    matchLabels:
      app: mongo-shard1
  template:
    metadata:
      labels:
        app: mongo-shard1
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          command: ["mongod", "--replSet", "shard1ReplSet", "--shardsvr", "--port", "27017", "--bind_ip_all"]
          volumeMounts:
            - name: shard1-storage
              mountPath: /data/db  # Mounting the volume at the specified path
      volumes:
        - name: shard1-storage
          emptyDir: {}  # Using an emptyDir for ephemeral storage
