apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-test-client
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: mongo-test-client
  template:
    metadata:
      labels:
        app: mongo-test-client
    spec:
      nodeName: worker5
      containers:
        - name: mongo-test-client
          image: joaomacas02/mongo-test-client
          ports:
            - containerPort: 8080  # Change this if your application uses a different port
