---
- hosts: master
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Delete Kubernetes configurations
      command: kubectl delete -f /home/ubuntu/{{ item }}  # Adjust the path to where your YAML files are
      loop:
        - mongo-cfg.yaml
        - mongo-mongos.yaml
        - mongo-services.yaml
        - mongo-shard1.yaml
        - mongo-shard2.yaml
        - mongo-shard3.yaml
        - mongo-test-client.yaml
        - mongo-shard4.yaml
        - mongo-shard5.yaml
      ignore_errors: yes  # This will ignore errors if the file doesn't exist
